/*
 * GraphQL mutation strings.
 *
 * Use autogenerated graphql/mutations for reference if needed.
 */

export const createPost = /* GraphQL */ `
  mutation CreatePost(
    $input: CreatePostInput!
    $condition: ModelPostConditionInput
  ) {
    createPost(input: $input, condition: $condition) {
      id
      published
      publishDate
      deprecated
      s3id
      title
      authorID
      mapID
      tags
      description
      markdown
      sanitizedHtml
      images {
        key
        url
      }
      createdAt
      updatedAt
      map {
        name
      }
      author {
        cognitoUserSud
        username
        profilePic {
          key
          url
        }
      }
    }
  }
`;
export const updatePost = /* GraphQL */ `
  mutation UpdatePost(
    $input: UpdatePostInput!
    $condition: ModelPostConditionInput
  ) {
    updatePost(input: $input, condition: $condition) {
      id
      published
      publishDate
      deprecated
      s3id
      title
      authorID
      mapID
      tags
      description
      markdown
      sanitizedHtml
      images {
        key
        url
      }
      createdAt
      updatedAt
      map {
        name
      }
      author {
        cognitoUserSud
        username
        profilePic {
          key
          url
        }
      }
    }
  }
`;
export const deletePost = /* GraphQL */ `
  mutation DeletePost(
    $input: DeletePostInput!
    $condition: ModelPostConditionInput
  ) {
    deletePost(input: $input, condition: $condition) {
      id
      published
      publishDate
      deprecated
      s3id
      title
      authorID
      mapID
      tags
      description
      markdown
      sanitizedHtml
      images {
        key
        url
      }
      createdAt
      updatedAt
    }
  }
`;
export const createAuthor = /* GraphQL */ `
  mutation CreateAuthor(
    $input: CreateAuthorInput!
    $condition: ModelAuthorConditionInput
  ) {
    createAuthor(input: $input, condition: $condition) {
      id
      cognitoUserSud
      username
      profilePic {
        key
        url
      }
      bio
      createdAt
      updatedAt
    }
  }
`;
