/*
 * GraphQL query strings.
 *
 * Use autogenerated graphql/mutations for reference if needed.
 */

/*
 * MAPS
 */
export const listMaps = /* GraphQL */ `
  query ListMaps(
    $filter: ModelMapFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listMaps(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        name
        canonicalName
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

/*
 * POSTS
 */
export const getPost = /* GraphQL */ `
  query GetPost($id: ID!) {
    getPost(id: $id) {
      id
      published
      publishDate
      deprecated
      s3id
      title
      authorID
      mapID
      tags
      description
      markdown
      sanitizedHtml
      images {
        key
        url
      }
      createdAt
      updatedAt
      map {
        name
        canonicalName
      }
      author {
        cognitoUserSud
        username
        profilePic {
          key
          url
        }
      }
    }
  }
`;
export const listPosts = /* GraphQL */ `
  query ListPosts(
    $filter: ModelPostFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listPosts(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        published
        publishDate
        deprecated
        s3id
        title
        authorID
        mapID
        tags
        description
        markdown
        sanitizedHtml
        images {
          key
          url
        }
        createdAt
        updatedAt
        map {
          name
          canonicalName
        }
        author {
          cognitoUserSud
          username
          profilePic {
            key
            url
          }
        }
      }
      nextToken
    }
  }
`;
export const searchPosts = /* GraphQL */ `
  query SearchPosts(
    $filter: SearchablePostFilterInput
    $sort: SearchablePostSortInput
    $limit: Int
    $nextToken: String
  ) {
    searchPosts(
      filter: $filter
      sort: $sort
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        published
        publishDate
        deprecated
        s3id
        title
        authorID
        mapID
        tags
        description
        markdown
        sanitizedHtml
        images {
          key
          url
        }
        createdAt
        updatedAt
        map {
          name
          canonicalName
        }
        author {
          cognitoUserSud
          username
          profilePic {
            key
            url
          }
        }
      }
      nextToken
      total
    }
  }
`;
export const searchPostTitlesAndIds = /* GraphQL */ `
  query searchPostTitlesAndIds(
    $filter: SearchablePostFilterInput
    $sort: SearchablePostSortInput
  ) {
    searchPosts(
      filter: $filter
      sort: $sort
    ) {
      items {
        id
        title
        published
      }
    }
  }
`;

/*
 * AUTHORS
 */
export const getAuthor = /* GraphQL */ `
  query GetAuthor($cognitoUserSud: String!) {
    getAuthor(cognitoUserSud: $cognitoUserSud) {
      id
      cognitoUserSud
      username
      profilePic {
        key
        url
      }
      bio
      createdAt
      updatedAt
    }
  }
`;